export const IMGLIST_CHANGE = 'IMGLIST_CHANGE/MODEL';
export const STATUS_CHANGE  = 'STATUS_CHANGE/MODEL';
export const SLIDE_STATUS_CHANGE = 'SLIDE_STATUS_CHANGE/MODEL';
export const SELECT_INDEX_CHANGE = 'SELECT_INDEX_CHANGE/MODEL';